server:
  port: 10087
spring:
  application:
      name: eureka-server # eureka的service id
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  server:
    eviction-interval-timer-in-ms: 60000
    enable-self-preservation: true
