//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment
    {
        public int PostId { get; set; }
        public string PostName { get; set; }
        public string PostType { get; set; }
        public string PostPlace { get; set; }
        public string PostDesc { get; set; }
        public string PostRequire { get; set; }
        public string Experience { get; set; }
        public string EduBackground { get; set; }
        public Nullable<int> RequireCount { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public string Manager { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    }
}
