//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsId { get; set; }
        public string NewsTitle { get; set; }
        public string NewsContents { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual NewsCategory NewsCategory { get; set; }
    }
}
