//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Suggestion
    {
        public int SuggestionId { get; set; }

        [DisplayName("客户名称")]
        [Required(ErrorMessage ="{0}不能为空")]
        public string CustomerName { get; set; }

        [DisplayName("消费详情")]
        [Required(ErrorMessage ="{0}不能为空")]
        public string ConsumeDesc { get; set; }

        [DisplayName("建议内容")]
        [Required(ErrorMessage = "{0}不能为空")]
        public string SuggestionDesc { get; set; }

        public Nullable<System.DateTime> SuggestionTime { get; set; }

        [DisplayName("手机号")]
        [Required(ErrorMessage = "{0}不能为空")]
        [RegularExpression(@"^(13[0-9]|14[5|7]|15[0|1|2|3|5|6|7|8|9]|18[0|1|2|3|5|6|7|8|9])\d{8}$", ErrorMessage = "请输入正确的{0}")]
        public string PhoneNumber { get; set; }

        [DisplayName("电子邮件")]
        [Required(ErrorMessage = "{0}不能为空")]
        [RegularExpression(@"^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "请输入正确的{0}")]
        public string Email { get; set; }

        public Nullable<int> StatusId { get; set; } = 0;
    }
}
