server:
  port: 10010
spring:
  application:
    name: gateway # eureka的service id
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
zuul:
  ignored-services:
    - user-service
  routes:
    consumer:
      path: /consumer/**
      serviceId: CONSUMER
      stripPrefix: false # 不去除匹配前缀
