//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishesBook
    {
        public int BookId { get; set; }
        public string HotelName { get; set; }
        public Nullable<System.DateTime> ConsumeTime { get; set; }
        public Nullable<int> ConsumePersons { get; set; }
        public string RoomType { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> BookTime { get; set; }
        public Nullable<int> OrderStatus { get; set; }
    }
}
