//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SysAdmins
    {
        [DisplayName("登录ID")]
        [Required(ErrorMessage ="{0}不能为空")]
        public int LoginId { get; set; }
        public string LoginName { get; set; }
        [DisplayName("登录密码")]
        [Required(ErrorMessage = "{0}不能为空")]
        public string LoginPwd { get; set; }
    }
}
